# Generated by Django 5.1.4 on 2026-01-15 07:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("goals", "0004_goal_shared_with_groups_goal_visibility"),
        ("groups", "0001_initial"),
        ("tasks", "0007_task_shared_with_groups_task_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "progress_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall completion percentage (0-100)",
                        verbose_name="progress percentage",
                    ),
                ),
                (
                    "velocity",
                    models.FloatField(
                        default=0.0,
                        help_text="Progress percentage per day",
                        verbose_name="velocity",
                    ),
                ),
                (
                    "velocity_trend",
                    models.CharField(
                        choices=[
                            ("accelerating", "Accelerating"),
                            ("steady", "Steady"),
                            ("slowing", "Slowing"),
                            ("stalled", "Stalled"),
                        ],
                        default="steady",
                        max_length=20,
                        verbose_name="velocity trend",
                    ),
                ),
                (
                    "milestones_total",
                    models.PositiveIntegerField(default=0, verbose_name="total milestones"),
                ),
                (
                    "milestones_completed",
                    models.PositiveIntegerField(default=0, verbose_name="completed milestones"),
                ),
                ("tasks_total", models.PositiveIntegerField(default=0, verbose_name="total tasks")),
                (
                    "tasks_completed",
                    models.PositiveIntegerField(default=0, verbose_name="completed tasks"),
                ),
                (
                    "estimated_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="Predicted completion date based on current velocity",
                        null=True,
                        verbose_name="estimated completion",
                    ),
                ),
                (
                    "days_ahead_or_behind",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = ahead of schedule, Negative = behind",
                        verbose_name="days ahead/behind",
                    ),
                ),
                (
                    "on_track",
                    models.BooleanField(
                        default=True,
                        help_text="Whether goal is on track to meet deadline",
                        verbose_name="on track",
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(blank=True, null=True, verbose_name="last activity"),
                ),
                (
                    "days_since_activity",
                    models.PositiveIntegerField(default=0, verbose_name="days since activity"),
                ),
                (
                    "goal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_stats",
                        to="goals.goal",
                        verbose_name="goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "goal progress",
                "verbose_name_plural": "goal progress records",
            },
        ),
        migrations.CreateModel(
            name="HabitPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "consistency_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of periods where target was met (0-100)",
                        verbose_name="consistency rate",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current consecutive periods with completion",
                        verbose_name="current streak",
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest streak ever", verbose_name="longest streak"
                    ),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                            ("at_risk", "At Risk"),
                        ],
                        default="stable",
                        max_length=20,
                        verbose_name="trend",
                    ),
                ),
                (
                    "last_completion_date",
                    models.DateField(blank=True, null=True, verbose_name="last completion"),
                ),
                (
                    "completions_last_7_days",
                    models.PositiveIntegerField(default=0, verbose_name="completions (7 days)"),
                ),
                (
                    "completions_last_30_days",
                    models.PositiveIntegerField(default=0, verbose_name="completions (30 days)"),
                ),
                (
                    "total_completions",
                    models.PositiveIntegerField(default=0, verbose_name="total completions"),
                ),
                (
                    "completion_heatmap",
                    models.JSONField(
                        default=dict,
                        help_text="Daily completion counts for heatmap visualization",
                        verbose_name="completion heatmap",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        limit_choices_to={"is_recurring": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="tasks.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "habit performance",
                "verbose_name_plural": "habit performances",
            },
        ),
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current consecutive days with completed tasks",
                        verbose_name="current streak",
                    ),
                ),
                (
                    "current_streak_start",
                    models.DateField(
                        blank=True,
                        help_text="When the current streak started",
                        null=True,
                        verbose_name="current streak start",
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True,
                        help_text="Last date with completed task",
                        null=True,
                        verbose_name="last activity date",
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Longest streak ever achieved",
                        verbose_name="longest streak",
                    ),
                ),
                (
                    "longest_streak_start",
                    models.DateField(blank=True, null=True, verbose_name="longest streak start"),
                ),
                (
                    "longest_streak_end",
                    models.DateField(blank=True, null=True, verbose_name="longest streak end"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user streak",
                "verbose_name_plural": "user streaks",
            },
        ),
        migrations.CreateModel(
            name="DailyProductivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "tasks_completed",
                    models.PositiveIntegerField(default=0, verbose_name="tasks completed"),
                ),
                (
                    "tasks_created",
                    models.PositiveIntegerField(default=0, verbose_name="tasks created"),
                ),
                (
                    "habit_completions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of recurring task completions",
                        verbose_name="habit completions",
                    ),
                ),
                (
                    "total_time_spent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total minutes spent on tasks",
                        verbose_name="total time spent",
                    ),
                ),
                (
                    "completions_by_hour",
                    models.JSONField(
                        default=dict,
                        help_text="Task completions breakdown by hour (0-23)",
                        verbose_name="completions by hour",
                    ),
                ),
                (
                    "milestones_completed",
                    models.PositiveIntegerField(default=0, verbose_name="milestones completed"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily productivity",
                "verbose_name_plural": "daily productivity records",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["user", "date"], name="stats_daily_user_id_c88159_idx"),
                    models.Index(fields=["date"], name="stats_daily_date_31525f_idx"),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="GroupRanking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "rank",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the group (1 = top)", verbose_name="rank"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("week", "Week"), ("month", "Month")],
                        default="week",
                        max_length=10,
                        verbose_name="period type",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="period start")),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("habit_completions", models.PositiveIntegerField(default=0)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                ("goals_progress", models.FloatField(default=0.0)),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Weighted score for ranking",
                        verbose_name="total score",
                    ),
                ),
                (
                    "rank_change",
                    models.IntegerField(
                        default=0,
                        help_text="Positive = moved up, Negative = moved down",
                        verbose_name="rank change",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rankings",
                        to="groups.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_rankings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "group ranking",
                "verbose_name_plural": "group rankings",
                "ordering": ["rank"],
                "indexes": [
                    models.Index(
                        fields=["group", "period_type", "period_start", "rank"],
                        name="stats_group_group_i_7e5a3e_idx",
                    )
                ],
                "unique_together": {("group", "user", "period_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="PeriodComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "period_type",
                    models.CharField(
                        choices=[("week", "Week"), ("month", "Month")],
                        max_length=10,
                        verbose_name="period type",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="period start")),
                ("period_end", models.DateField(verbose_name="period end")),
                ("tasks_completed", models.PositiveIntegerField(default=0)),
                ("tasks_created", models.PositiveIntegerField(default=0)),
                ("habit_completions", models.PositiveIntegerField(default=0)),
                ("time_spent_minutes", models.PositiveIntegerField(default=0)),
                ("goals_progressed", models.PositiveIntegerField(default=0)),
                ("milestones_completed", models.PositiveIntegerField(default=0)),
                (
                    "tasks_change_percent",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage change from previous period",
                        verbose_name="tasks change %",
                    ),
                ),
                (
                    "productivity_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Computed productivity score (0-100)",
                        verbose_name="productivity score",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_comparisons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "period comparison",
                "verbose_name_plural": "period comparisons",
                "ordering": ["-period_start"],
                "unique_together": {("user", "period_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="PersonalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("max_tasks_day", "Most tasks in a day"),
                            ("max_tasks_week", "Most tasks in a week"),
                            ("max_habits_day", "Most habits in a day"),
                            ("longest_streak", "Longest streak"),
                            ("fastest_goal", "Fastest goal completion"),
                            ("most_productive_hour", "Most productive hour"),
                            ("best_week", "Best week ever"),
                            ("best_month", "Best month ever"),
                        ],
                        max_length=30,
                        verbose_name="record type",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="Record value (tasks count, days, etc.)", verbose_name="value"
                    ),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="achieved at"
                    ),
                ),
                (
                    "achieved_date",
                    models.DateField(
                        help_text="Date when record was set", verbose_name="achieved date"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the record",
                        verbose_name="context",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current record (not beaten)",
                        verbose_name="is current",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "personal record",
                "verbose_name_plural": "personal records",
                "ordering": ["-achieved_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "record_type", "is_current"],
                        name="stats_perso_user_id_b9499c_idx",
                    )
                ],
            },
        ),
    ]
