# Generated by Django 5.1.4 on 2026-01-07 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "title",
                    models.CharField(help_text="Task title", max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of the task",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for completing the task",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this task repeats on a schedule",
                        verbose_name="is recurring",
                    ),
                ),
                (
                    "recurrence_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        help_text="How often the task should be completed (always starts from calendar boundaries)",
                        max_length=20,
                        null=True,
                        verbose_name="recurrence period",
                    ),
                ),
                (
                    "recurrence_target_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="How many times the task should be completed per period (e.g., 3 times per week)",
                        null=True,
                        verbose_name="target completions per period",
                    ),
                ),
                (
                    "recurrence_end_date",
                    models.DateField(
                        blank=True,
                        help_text="When the recurring schedule ends (optional)",
                        null=True,
                        verbose_name="recurrence end date",
                    ),
                ),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated time to complete the task in minutes",
                        null=True,
                        verbose_name="estimated duration (minutes)",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated tags",
                        max_length=500,
                        verbose_name="tags",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="completed at"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional notes about this completion",
                        verbose_name="notes",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long it actually took to complete",
                        null=True,
                        verbose_name="actual duration (minutes)",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="tasks.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "task completion",
                "verbose_name_plural": "task completions",
                "ordering": ["-completed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_task_status_4a0a95_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="tasks_task_priorit_a900d4_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_task_due_dat_bce847_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["user", "status"], name="tasks_task_user_id_c0fce1_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["is_recurring"], name="tasks_task_is_recu_cea9ca_idx"),
        ),
        migrations.AddIndex(
            model_name="taskcompletion",
            index=models.Index(
                fields=["task", "completed_at"], name="tasks_taskc_task_id_ef82fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskcompletion",
            index=models.Index(fields=["completed_at"], name="tasks_taskc_complet_bc53fb_idx"),
        ),
    ]
