# Generated by Django 5.1.4 on 2026-01-10 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_unit_type_target_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskcompletion",
            name="completed_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Completed amount in the task's unit (minutes, hours, or count)",
                null=True,
                verbose_name="completed value",
            ),
        ),
        migrations.AlterField(
            model_name="taskcompletion",
            name="completed_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="completed at"
            ),
        ),
        migrations.AlterField(
            model_name="taskcompletion",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How long it actually took to complete (legacy, use completed_value)",
                null=True,
                verbose_name="actual duration (minutes)",
            ),
        ),
    ]
