# Generated by Django 5.1.4 on 2026-01-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskcompletion_completed_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="custom_unit_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name for custom unit (used when unit_type is 'custom')",
                max_length=50,
                verbose_name="custom unit name",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="target_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target value in the specified unit (e.g., 30 minutes, 50 pages)",
                null=True,
                verbose_name="target value",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="unit_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("minutes", "Minutes"),
                    ("hours", "Hours"),
                    ("count", "Count/Repetitions"),
                    ("pages", "Pages"),
                    ("kilometers", "Kilometers"),
                    ("meters", "Meters"),
                    ("calories", "Calories"),
                    ("steps", "Steps"),
                    ("custom", "Custom unit"),
                ],
                help_text="Type of unit for measuring the goal",
                max_length=20,
                null=True,
                verbose_name="unit type",
            ),
        ),
    ]
