# Generated by Django 5.1.4 on 2026-01-13 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_goal_icon"),
        ("tasks", "0004_task_custom_unit_name_alter_task_target_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Goal this task belongs to (auto-deleted with goal)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="goals.goal",
                verbose_name="goal",
            ),
        ),
    ]
