# Generated by Django 5.1.4 on 2026-01-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        ("tasks", "0006_taskgroup_task_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="shared_with_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Groups this task is shared with (when visibility is 'group')",
                related_name="shared_tasks",
                to="groups.group",
                verbose_name="shared with groups",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("group", "Group"), ("public", "Public")],
                default="private",
                help_text="Who can see this task",
                max_length=10,
                verbose_name="visibility",
            ),
        ),
    ]
