# Generated by Django 5.1.4 on 2026-01-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_shared_with_groups_task_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this recurring task is active (inactive tasks won't generate new completions)",
                verbose_name="is active",
            ),
        ),
    ]
