# Generated by Django 5.1.4 on 2026-04-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_task_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user stops working on this task",
                null=True,
                verbose_name="end datetime",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user starts working on this task",
                null=True,
                verbose_name="start datetime",
            ),
        ),
    ]
