# Generated by Django 5.1.4 on 2026-04-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlanExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("target_sets", models.PositiveIntegerField()),
                ("target_reps", models.PositiveIntegerField()),
                ("rest_time_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_links",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_exercises",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="workouts.workoutplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_exercises",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_exercises",
                        to="workouts.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("set_number", models.PositiveIntegerField()),
                ("reps", models.PositiveIntegerField()),
                ("weight", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_sets",
                        to="workouts.sessionexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
                "indexes": [
                    models.Index(
                        fields=["session_exercise", "set_number"],
                        name="workouts_ex_session_3edcc1_idx",
                    ),
                    models.Index(fields=["created_at"], name="workouts_ex_created_9b902d_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_exercise", "set_number"),
                        name="uniq_session_exercise_set_number",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["user", "started_at"], name="workouts_wo_user_id_a223bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["user", "created_at"], name="workouts_wo_user_id_a4981b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutplanexercise",
            index=models.Index(
                fields=["workout_plan", "order"], name="workouts_wo_workout_b63956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutplanexercise",
            index=models.Index(fields=["exercise"], name="workouts_wo_exercis_2e7306_idx"),
        ),
        migrations.AddConstraint(
            model_name="workoutplanexercise",
            constraint=models.UniqueConstraint(
                fields=("workout_plan", "order"), name="uniq_workout_plan_order"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["user", "started_at"], name="workouts_wo_user_id_d379c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workoutsession",
            index=models.Index(
                fields=["workout_plan", "started_at"], name="workouts_wo_workout_10f6bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionexercise",
            index=models.Index(fields=["session", "order"], name="workouts_se_session_7b9670_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionexercise",
            index=models.Index(
                fields=["exercise", "started_at"], name="workouts_se_exercis_b43e92_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionexercise",
            constraint=models.UniqueConstraint(
                fields=("session", "order"), name="uniq_session_order"
            ),
        ),
    ]
