"""
Domain entities for Goals.

These are pure dataclasses representing the domain without
framework-specific concerns.
"""

from dataclasses import dataclass, field
from datetime import date
from typing import List, Optional


@dataclass
class GeneratedQuestion:
    """Single clarifying question generated by LLM."""

    id: str
    question: str
    type: str = "text"  # text | choice | number
    placeholder: str = ""
    options: List[str] = field(default_factory=list)


@dataclass
class QuestionAnswer:
    """Answer provided by user to a generated question."""

    question_id: str
    question: str
    answer: str


@dataclass
class GeneratedTask:
    """Task suggestion within a milestone."""

    title: str
    description: str
    estimated_duration: str
    priority: str  # high | medium | low
    is_recurring: bool = False
    recurrence_period: Optional[str] = None
    category: str = "learning"  # preparation | learning | practice | review | achievement


@dataclass
class GeneratedMilestone:
    """Milestone suggested by the LLM."""

    title: str
    description: str
    target_date: date
    tasks: List[GeneratedTask] = field(default_factory=list)
    requirements: str = ""
    success_criteria: str = ""


@dataclass
class GeneratedPlan:
    """Full plan returned by the LLM."""

    summary: str
    milestones: List[GeneratedMilestone]
    tips: List[str] = field(default_factory=list)
    potential_obstacles: List[str] = field(default_factory=list)
    motivation: str = ""
    final_achievement: str = ""
    icon: str = ""
