"""
Goal models for long-term goal planning with AI-assisted breakdown.

Structure:
- Goal: Main long-term goal with LLM-generated plan
- Milestone: Key checkpoints within a goal
- Tasks can be linked to Milestones via bridge table
"""

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from apps.tasks.models import TimeStampedModel


class Goal(TimeStampedModel):
    """
    Long-term goal with AI-generated planning.

    A Goal represents a significant life objective that takes weeks/months to achieve.
    Users answer questions about the goal, and an LLM generates a structured plan
    with milestones and suggested tasks.
    """

    class Status(models.TextChoices):
        DRAFT = "draft", _("Draft")  # Goal created but plan not yet generated
        PLANNING = "planning", _("Planning")  # LLM is generating the plan
        ACTIVE = "active", _("Active")  # Goal is being worked on
        PAUSED = "paused", _("Paused")  # Temporarily on hold
        COMPLETED = "completed", _("Completed")  # Goal achieved!
        ABANDONED = "abandoned", _("Abandoned")  # Goal was abandoned

    class Category(models.TextChoices):
        HEALTH = "health", _("Health & Fitness")
        CAREER = "career", _("Career & Professional")
        EDUCATION = "education", _("Education & Learning")
        FINANCE = "finance", _("Finance & Wealth")
        RELATIONSHIPS = "relationships", _("Relationships & Social")
        CREATIVITY = "creativity", _("Creativity & Hobbies")
        PERSONAL = "personal", _("Personal Growth")
        OTHER = "other", _("Other")

    # Basic fields
    title = models.CharField(
        _("title"),
        max_length=255,
        help_text=_("What do you want to achieve?"),
    )
    description = models.TextField(
        _("description"),
        blank=True,
        default="",
        help_text=_("Detailed description of your goal"),
    )

    # Categorization
    category = models.CharField(
        _("category"),
        max_length=20,
        choices=Category.choices,
        default=Category.PERSONAL,
    )

    # Status
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
    )

    # Timeframe
    start_date = models.DateField(
        _("start date"),
        null=True,
        blank=True,
        help_text=_("When do you want to start working on this goal?"),
    )
    target_date = models.DateField(
        _("target date"),
        help_text=_("When do you want to achieve this goal?"),
    )
    completed_at = models.DateTimeField(
        _("completed at"),
        null=True,
        blank=True,
    )

    # User
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="goals",
        verbose_name=_("user"),
    )

    # LLM Planning data
    planning_questions = models.JSONField(
        _("planning questions"),
        default=list,
        blank=True,
        help_text=_("LLM-generated questions specific to this goal"),
    )
    planning_answers = models.JSONField(
        _("planning answers"),
        default=list,
        blank=True,
        help_text=_("User's answers to planning questions"),
    )
    llm_generated_plan = models.JSONField(
        _("LLM generated plan"),
        null=True,
        blank=True,
        help_text=_("The full plan generated by LLM (stored for reference)"),
    )
    plan_generated_at = models.DateTimeField(
        _("plan generated at"),
        null=True,
        blank=True,
    )

    # Motivation & context
    motivation = models.TextField(
        _("motivation"),
        blank=True,
        default="",
        help_text=_("Why is this goal important to you? (from LLM or user)"),
    )
    potential_obstacles = models.JSONField(
        _("potential obstacles"),
        default=list,
        blank=True,
        help_text=_("List of potential obstacles identified"),
    )
    tips = models.JSONField(
        _("tips"),
        default=list,
        blank=True,
        help_text=_("Tips and advice for achieving the goal"),
    )
    final_achievement = models.TextField(
        _("final achievement"),
        blank=True,
        default="",
        help_text=_("Concrete description of what 'success' looks like"),
    )
    icon = models.CharField(
        _("icon"),
        max_length=64,
        blank=True,
        default="",
        help_text=_("Optional icon name for the goal (e.g., material-community icon key)"),
    )

    class Meta:
        verbose_name = _("goal")
        verbose_name_plural = _("goals")
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["user", "status"]),
            models.Index(fields=["status"]),
            models.Index(fields=["target_date"]),
            models.Index(fields=["category"]),
        ]

    def __str__(self):
        return self.title

    @property
    def progress_percentage(self) -> float:
        """Calculate overall progress based on completed milestones."""
        total = self.milestones.count()
        if total == 0:
            return 0.0
        completed = self.milestones.filter(status=Milestone.Status.COMPLETED).count()
        return round((completed / total) * 100, 1)

    @property
    def days_remaining(self) -> int | None:
        """Calculate days until target date."""
        if not self.target_date:
            return None
        from django.utils import timezone

        today = timezone.now().date()
        delta = self.target_date - today
        return delta.days

    @property
    def is_overdue(self) -> bool:
        """Check if goal is past target date and not completed."""
        if self.status == self.Status.COMPLETED:
            return False
        days = self.days_remaining
        return days is not None and days < 0


class Milestone(TimeStampedModel):
    """
    A milestone represents a key checkpoint within a goal.

    Milestones break down a large goal into manageable chunks,
    each with its own target date and set of tasks.
    """

    class Status(models.TextChoices):
        PENDING = "pending", _("Pending")  # Not started yet
        IN_PROGRESS = "in_progress", _("In Progress")  # Currently working on
        COMPLETED = "completed", _("Completed")  # Done!
        SKIPPED = "skipped", _("Skipped")  # Decided to skip this milestone

    # Relation to Goal
    goal = models.ForeignKey(
        Goal,
        on_delete=models.CASCADE,
        related_name="milestones",
        verbose_name=_("goal"),
    )

    # Basic fields
    title = models.CharField(
        _("title"),
        max_length=255,
        help_text=_("Milestone title"),
    )
    description = models.TextField(
        _("description"),
        blank=True,
        default="",
        help_text=_("What does achieving this milestone mean?"),
    )

    # Status
    status = models.CharField(
        _("status"),
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )

    # Ordering within goal
    order = models.PositiveIntegerField(
        _("order"),
        default=0,
        help_text=_("Order within the goal (0 = first)"),
    )

    # Timeframe
    target_date = models.DateField(
        _("target date"),
        null=True,
        blank=True,
        help_text=_("When should this milestone be completed?"),
    )
    completed_at = models.DateTimeField(
        _("completed at"),
        null=True,
        blank=True,
    )

    # Requirements & notes
    requirements = models.TextField(
        _("requirements"),
        blank=True,
        default="",
        help_text=_("What's needed before starting this milestone?"),
    )
    success_criteria = models.TextField(
        _("success criteria"),
        blank=True,
        default="",
        help_text=_("How to know this milestone is complete"),
    )
    notes = models.TextField(
        _("notes"),
        blank=True,
        default="",
        help_text=_("Additional notes"),
    )

    # LLM-suggested tasks (stored as JSON before being converted to actual Tasks)
    suggested_tasks = models.JSONField(
        _("suggested tasks"),
        default=list,
        blank=True,
        help_text=_("Tasks suggested by LLM (before user creates actual Task objects)"),
    )

    class Meta:
        verbose_name = _("milestone")
        verbose_name_plural = _("milestones")
        ordering = ["goal", "order", "target_date"]
        indexes = [
            models.Index(fields=["goal", "status"]),
            models.Index(fields=["goal", "order"]),
            models.Index(fields=["target_date"]),
        ]

    def __str__(self):
        return f"{self.goal.title} - {self.title}"

    @property
    def task_count(self) -> int:
        """Get number of linked tasks."""
        return self.task_links.count()

    @property
    def completed_task_count(self) -> int:
        """Get number of completed linked tasks."""
        from apps.tasks.models import Task

        return Task.objects.filter(
            milestone_links__milestone=self,
            status=Task.Status.COMPLETED,
        ).count()

    @property
    def progress_percentage(self) -> float:
        """Calculate progress based on completed tasks."""
        total = self.task_count
        if total == 0:
            # If no tasks, consider suggested tasks
            suggested = len(self.suggested_tasks) if self.suggested_tasks else 0
            if suggested == 0:
                return 100.0 if self.status == self.Status.COMPLETED else 0.0
            return 0.0
        return round((self.completed_task_count / total) * 100, 1)

    @property
    def days_remaining(self) -> int | None:
        """Calculate days until target date."""
        if not self.target_date:
            return None
        from django.utils import timezone

        today = timezone.now().date()
        delta = self.target_date - today
        return delta.days

    @property
    def is_overdue(self) -> bool:
        """Check if milestone is past target date and not completed."""
        if self.status in [self.Status.COMPLETED, self.Status.SKIPPED]:
            return False
        days = self.days_remaining
        return days is not None and days < 0

    def mark_completed(self):
        """Mark milestone as completed."""
        from django.utils import timezone

        self.status = self.Status.COMPLETED
        self.completed_at = timezone.now()
        self.save(update_fields=["status", "completed_at", "updated_at"])


class MilestoneTaskLink(models.Model):
    """
    Bridge table linking Milestones to Tasks without coupling Task to Goals.
    """

    milestone = models.ForeignKey(
        Milestone,
        on_delete=models.CASCADE,
        related_name="task_links",
        verbose_name=_("milestone"),
    )
    task = models.ForeignKey(
        "tasks.Task",
        on_delete=models.CASCADE,
        related_name="milestone_links",
        verbose_name=_("task"),
    )
    created_at = models.DateTimeField(_("created at"), default=timezone.now)

    class Meta:
        verbose_name = _("milestone task link")
        verbose_name_plural = _("milestone task links")
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.milestone} -> {self.task}"
