# Generated by Django 5.1.4 on 2026-01-14 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "name",
                    models.CharField(
                        help_text="Group display name", max_length=100, verbose_name="name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Group description",
                        verbose_name="description",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique URL-friendly identifier",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Public groups can be discovered and joined by anyone",
                        verbose_name="is public",
                    ),
                ),
                (
                    "allow_member_invites",
                    models.BooleanField(
                        default=False,
                        help_text="Allow non-admin members to invite others",
                        verbose_name="allow member invites",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="👥",
                        help_text="Emoji icon for the group",
                        max_length=10,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366F1",
                        help_text="Hex color for the group",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "group",
                "verbose_name_plural": "groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "invited_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email address if inviting non-registered user",
                        max_length=254,
                        verbose_name="invited email",
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        help_text="Unique code for invite link",
                        max_length=32,
                        unique=True,
                        verbose_name="invite code",
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="assigned role",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When this invitation expires", verbose_name="expires at"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional invitation message",
                        verbose_name="message",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="groups.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited user",
                    ),
                ),
            ],
            options={
                "verbose_name": "group invitation",
                "verbose_name_plural": "group invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["invite_code"], name="groups_grou_invite__c86a0a_idx"),
                    models.Index(fields=["invited_email"], name="groups_grou_invited_a3af12_idx"),
                    models.Index(
                        fields=["status", "expires_at"], name="groups_grou_status_aae894_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive memberships are soft-deleted",
                        verbose_name="is active",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True, verbose_name="joined at")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="groups.group",
                        verbose_name="group",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "group membership",
                "verbose_name_plural": "group memberships",
                "ordering": ["-joined_at"],
                "unique_together": {("group", "user")},
            },
        ),
    ]
