# Generated by Django 5.1.4 on 2026-01-12 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug_report", "Bug Report"),
                            ("suggestion", "Suggestion"),
                            ("comment", "General Comment"),
                            ("question", "Question"),
                        ],
                        default="comment",
                        help_text="Type of feedback",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title/summary of the feedback", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Detailed description of the feedback")),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="App version when feedback was submitted",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, help_text="Device/OS information", max_length=200, null=True
                    ),
                ),
                (
                    "screen_name",
                    models.CharField(
                        blank=True,
                        help_text="Screen/route where user was when submitting feedback",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_review", "In Review"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("wont_fix", "Won't Fix"),
                        ],
                        default="new",
                        help_text="Current status of this feedback",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        help_text="Priority level (set by admin)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes from admin/developers", null=True
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="When this feedback was resolved", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who submitted this feedback",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="feedback_fe_user_id_3075a3_idx"
                    ),
                    models.Index(
                        fields=["feedback_type", "status"], name="feedback_fe_feedbac_ea2289_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="feedback_fe_status_212662_idx"
                    ),
                ],
            },
        ),
    ]
