# Generated by Django 5.1.4 on 2026-01-12 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0004_task_custom_unit_name_alter_task_target_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "title",
                    models.CharField(
                        help_text="What do you want to achieve?",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed description of your goal",
                        verbose_name="description",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Fitness"),
                            ("career", "Career & Professional"),
                            ("education", "Education & Learning"),
                            ("finance", "Finance & Wealth"),
                            ("relationships", "Relationships & Social"),
                            ("creativity", "Creativity & Hobbies"),
                            ("personal", "Personal Growth"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="When do you want to start working on this goal?",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        help_text="When do you want to achieve this goal?",
                        verbose_name="target date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "planning_questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="LLM-generated questions specific to this goal",
                        verbose_name="planning questions",
                    ),
                ),
                (
                    "planning_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User's answers to planning questions",
                        verbose_name="planning answers",
                    ),
                ),
                (
                    "llm_generated_plan",
                    models.JSONField(
                        blank=True,
                        help_text="The full plan generated by LLM (stored for reference)",
                        null=True,
                        verbose_name="LLM generated plan",
                    ),
                ),
                (
                    "plan_generated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="plan generated at"),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Why is this goal important to you? (from LLM or user)",
                        verbose_name="motivation",
                    ),
                ),
                (
                    "potential_obstacles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of potential obstacles identified",
                        verbose_name="potential obstacles",
                    ),
                ),
                (
                    "tips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tips and advice for achieving the goal",
                        verbose_name="tips",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "goal",
                "verbose_name_plural": "goals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "title",
                    models.CharField(
                        help_text="Milestone title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What does achieving this milestone mean?",
                        verbose_name="description",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order within the goal (0 = first)",
                        verbose_name="order",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(
                        blank=True,
                        help_text="When should this milestone be completed?",
                        null=True,
                        verbose_name="target date",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="completed at"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What's needed to complete this milestone?",
                        verbose_name="requirements",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Additional notes", verbose_name="notes"
                    ),
                ),
                (
                    "suggested_tasks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tasks suggested by LLM (before user creates actual Task objects)",
                        verbose_name="suggested tasks",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="goals.goal",
                        verbose_name="goal",
                    ),
                ),
            ],
            options={
                "verbose_name": "milestone",
                "verbose_name_plural": "milestones",
                "ordering": ["goal", "order", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneTaskLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created at"
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_links",
                        to="goals.milestone",
                        verbose_name="milestone",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_links",
                        to="tasks.task",
                        verbose_name="task",
                    ),
                ),
            ],
            options={
                "verbose_name": "milestone task link",
                "verbose_name_plural": "milestone task links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["user", "status"], name="goals_goal_user_id_7ad9fc_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["status"], name="goals_goal_status_ea0ea8_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["target_date"], name="goals_goal_target__1cd2e5_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["category"], name="goals_goal_categor_07c7bc_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["goal", "status"], name="goals_miles_goal_id_b9082b_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["goal", "order"], name="goals_miles_goal_id_38bb14_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(fields=["target_date"], name="goals_miles_target__bea2ee_idx"),
        ),
    ]
