# Generated by Django 5.1.4 on 2026-01-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="final_achievement",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Concrete description of what 'success' looks like",
                verbose_name="final achievement",
            ),
        ),
        migrations.AddField(
            model_name="milestone",
            name="success_criteria",
            field=models.TextField(
                blank=True,
                default="",
                help_text="How to know this milestone is complete",
                verbose_name="success criteria",
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="What's needed before starting this milestone?",
                verbose_name="requirements",
            ),
        ),
    ]
