# Generated by Django 5.1.4 on 2026-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goal_final_achievement_milestone_success_criteria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional icon name for the goal (e.g., material-community icon key)",
                max_length=64,
                verbose_name="icon",
            ),
        ),
    ]
