# Generated by Django 5.1.4 on 2026-01-14 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0006_taskgroup_task_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch for all notifications",
                        verbose_name="notifications enabled",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications on mobile",
                        verbose_name="push notifications enabled",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Receive notifications via email",
                        verbose_name="email notifications enabled",
                    ),
                ),
                (
                    "regular_task_reminders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of reminder times for regular tasks, e.g., ['6h', '1h']",
                        verbose_name="regular task reminder times",
                    ),
                ),
                (
                    "daily_reminder_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Remind about incomplete daily tasks",
                        verbose_name="daily recurring reminder",
                    ),
                ),
                (
                    "daily_reminder_hours_before",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Hours before midnight to send daily task reminder",
                        verbose_name="hours before day end",
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Don't send notifications during quiet hours",
                        verbose_name="quiet hours enabled",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default="22:00",
                        help_text="Start of quiet hours (HH:MM)",
                        verbose_name="quiet hours start",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        default="08:00",
                        help_text="End of quiet hours (HH:MM)",
                        verbose_name="quiet hours end",
                    ),
                ),
                (
                    "push_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expo push token for mobile notifications",
                        max_length=512,
                        verbose_name="push notification token",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_reminder", "Task Reminder"),
                            ("daily_reminder", "Daily Recurring Reminder"),
                            ("weekly_reminder", "Weekly Recurring Reminder"),
                            ("goal_reminder", "Goal Milestone Reminder"),
                        ],
                        default="task_reminder",
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Notification message body", verbose_name="body"),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When this notification should be sent",
                        verbose_name="scheduled for",
                    ),
                ),
                (
                    "reminder_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Unique key for this reminder type (e.g., '6h', '1h')",
                        max_length=50,
                        verbose_name="reminder key",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="sent at")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="error message"),
                ),
                ("sent_via_push", models.BooleanField(default=False, verbose_name="sent via push")),
                (
                    "sent_via_email",
                    models.BooleanField(default=False, verbose_name="sent via email"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tasks.task",
                        verbose_name="task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "scheduled_for"],
                        name="notificatio_user_id_00e66f_idx",
                    ),
                    models.Index(
                        fields=["task", "reminder_key"], name="notificatio_task_id_a439a7_idx"
                    ),
                ],
                "unique_together": {("task", "reminder_key", "scheduled_for")},
            },
        ),
    ]
