# Generated by Django 5.1.4 on 2026-01-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("task_reminder", "Task Reminder"),
                    ("daily_reminder", "Daily Recurring Reminder"),
                    ("weekly_reminder", "Weekly Recurring Reminder"),
                    ("goal_reminder", "Goal Milestone Reminder"),
                    ("warning", "Warning"),
                    ("deadline_warning", "Deadline Warning"),
                    ("suggestion", "Suggestion"),
                    ("tip", "Tip"),
                    ("congratulations", "Congratulations"),
                    ("achievement", "Achievement"),
                    ("streak", "Streak"),
                    ("info", "Information"),
                ],
                default="task_reminder",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
